version: 2.1
jobs:
  build:
#    branches:
#      only:
#        - vuepress
    docker:
      - image: circleci/node:lts
    environment:
      - GH_USER: nu00
      - GH_EMAIL: xiangminli00@qq.com
    steps:
      - add_ssh_keys:
          fingerprints:
            - 33:14:91:7f:a9:25:f4:a1:5e:cf:c0:6f:55:a1:7f:2b
      - checkout 
#      - restore_cache:
#          name: Restore Yarn Package Cache
#          keys:
#            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
#          command: yarn install --frozen-lockfile
          command: yarn
#      - save_cache:
#          name: Save Yarn Package Cache
#          key: yarn-packages-{{ checksum "yarn.lock" }}
#          paths:
#            - ~/.cache/yarn
      # git is needed by the deploy command
      - run: |
          git config --global user.email ${GH_EMAIL}
          git config --global user.name ${GH_USER}
      - run: yarn deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: vuepress